import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Calendar } from "@components/ui/calendar";
import { Button } from "@components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@components/ui/popover";
import { CalendarIcon, Filter } from "lucide-react";
import { format } from "date-fns";
import { es } from "date-fns/locale";
import { cn } from "@lib/utils"; // Asume lib/utils existe
export function AppointmentFilters({ selectedDate, onDateChange, selectedStatus, onStatusChange }) {
    return (_jsxs("div", { className: "flex items-center space-x-4 p-4 bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Filter, { className: "h-4 w-4 text-gray-500 dark:text-gray-400" }), _jsx("span", { className: "text-sm font-medium text-gray-700 dark:text-gray-300", children: "Filtros:" })] }), _jsxs(Popover, { children: [_jsx(PopoverTrigger, { asChild: true, children: _jsxs(Button, { variant: "outline", className: cn("justify-start text-left font-normal bg-white dark:bg-gray-700 border-gray-200 dark:border-gray-600 text-gray-900 dark:text-white", !selectedDate && "text-muted-foreground"), children: [_jsx(CalendarIcon, { className: "mr-2 h-4 w-4" }), selectedDate ? format(selectedDate, "dd 'de' MMMM, yyyy", { locale: es }) : "Seleccionar fecha"] }) }), _jsx(PopoverContent, { className: "w-auto p-0 bg-white dark:bg-gray-800 border-gray-200 dark:border-gray-700", align: "start", children: _jsx(Calendar, { mode: "single", selected: selectedDate, onSelect: onDateChange, initialFocus: true }) })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Button, { variant: selectedStatus === 'próximas' ? 'default' : 'outline', size: "sm", className: "dark:text-white dark:border-gray-600", onClick: () => onStatusChange('próximas'), children: "Pr\u00F3ximas" }), _jsx(Button, { variant: selectedStatus === 'pasadas' ? 'default' : 'outline', size: "sm", className: "dark:text-white dark:border-gray-600", onClick: () => onStatusChange('pasadas'), children: "Pasadas" }), _jsx(Button, { variant: "outline", size: "sm", className: "dark:text-white dark:border-gray-600", onClick: () => onDateChange(new Date()), children: "Hoy" })] }), (selectedDate || selectedStatus) && (_jsx(Button, { variant: "ghost", size: "sm", className: "dark:text-gray-300", onClick: () => { onDateChange(undefined); onStatusChange(undefined); }, children: "Limpiar filtros" }))] }));
}
