"""Add code column to appointments table

Revision ID: f93e8cee856d
Revises: ed50b001398e
Create Date: 2025-08-27 09:52:14.224226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93e8cee856d'
down_revision: Union[str, Sequence[str], None] = 'ed50b001398e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('code', sa.String(), nullable=False))
    op.add_column('appointments', sa.Column('type', sa.String(), nullable=False))
    op.add_column('appointments', sa.Column('cost', sa.Float(), nullable=True))
    op.add_column('appointments', sa.Column('status_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.alter_column('appointments', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'appointments', ['code'])
    op.create_foreign_key(None, 'appointments', 'appointment_statuses', ['status_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'time_slots', ['time_slot_id'], ['id'])
    op.drop_column('appointments', 'schedule_id')
    op.drop_column('appointments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='unique')
    op.alter_column('appointments', 'date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_column('appointments', 'is_paid')
    op.drop_column('appointments', 'status_id')
    op.drop_column('appointments', 'cost')
    op.drop_column('appointments', 'type')
    op.drop_column('appointments', 'code')
    # ### end Alembic commands ###
